# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='avg_rate_int',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='cal_use_int',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='max_rate_int',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='time_spent_time',
            field=models.IntegerField(),
        ),
    ]
