# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_auto_20170618_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_int', models.IntegerField()),
                ('time', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='date_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summarydetails',
            name='fk_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.Summary'),
        ),
    ]
