# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_auto_20170618_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarydetails',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
